task: 'UVvolume_ZJU'
gpus: [0]

parent_cfg: 'configs/cmu_exp/p4s6.yaml'

train_dataset:
    data_root: 'data/zju_mocap/CoreView_313'
    human: 'CoreView_313'
    ann_file: 'data/zju_mocap/CoreView_313/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_313'
    human: 'CoreView_313'
    ann_file: 'data/zju_mocap/CoreView_313/annots.npy'
    split: 'test'

# data options
H: 1024
W: 1024
ratio: 0.5
training_view: [0,1,2,3,4,6,7,8,9,10,12,13,14,15,16,17,18,19,20]
test_view: [5,11]
num_train_frame: 100
begin_ith_frame: 0
frame_interval: 5
vertices: 'new_vertices'
params: 'new_params'
densepose: 'densepose'
mask: 'mask_cihp'
ignore_boundary: True
box_padding: 0.05
nv: 6890
pose_dim: 72
