task: 'UVvolume_wild'
gpus: [5,6,7]

parent_cfg: '/home/yjli/AIGC/Adversarial_camou/UV_Volumes/configs/cmu_exp/p4s6.yaml'

train_dataset:
    data_root: '/home/yjli/AIGC/Adversarial_camou/my_dataset/Peter_humannerf'
    human: 'Peter'
    ann_file: '/home/yjli/AIGC/humannerf/dataset/zju_mocap/CoreView_377/annots.npy'
    split: 'train'

test_dataset:
    data_root: '/home/yjli/AIGC/Adversarial_camou/my_dataset/Peter_humannerf'
    human: 'Peter'
    ann_file: '/home/yjli/AIGC/Adversarial_camou/my_dataset/Peter_humannerf/annots.npy'
    split: 'test'

# data options
H: 960
W: 960
ratio: 0.5
training_view: [1]
test_view: [1]
num_train_frame: 173
begin_ith_frame: 0
frame_interval: 1
vertices: 'new_vertices'
params: 'new_params'
densepose: 'densepose'
mask: 'masks'
ignore_boundary: True
box_padding: 0.05
nv: 6890
pose_dim: 72

voxel_size: [0.005, 0.005, 0.005]  # dhw
N_samples: 64