task: 'UVvolume_H36M'
gpus: [0]

parent_cfg: 'configs/cmu_exp/p4s6.yaml'

train_dataset:
    data_root: 'data/h36m/S6/Posing/'
    human: 'S6'
    ann_file: 'data/h36m/S6/Posing/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/h36m/S6/Posing/'s
    human: 'S6'
    ann_file: 'data/h36m/S6/Posing/annots.npy'
    split: 'test'

# data options
H: 1000
W: 1000
ratio: 1.
training_view: [0, 1, 2]
test_view: [3]
num_train_frame: 200
begin_ith_frame: 0
frame_interval: 5
vertices: 'new_vertices'
params: 'new_params'
densepose: 'densepose'
mask: 'mask_cihp'
ignore_boundary: True
box_padding: 0.05
nv: 6890
pose_dim: 72